version: '3.8'
services:
  oddsbooking-web:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-booking/web-oddsbooking:dev
    ports:
      - 80:80
    restart: always
    depends_on:
      - oddsbooking-api
  oddsbooking-api:
    image: swr.ap-southeast-2.myhuaweicloud.com/odds-booking/api-oddsbooking:dev
    ports:
      - 8081:8080
    restart: always
networks:
  default:
    name: oddsbooking-network

      

